# Generated by Django 4.2.3 on 2023-07-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss_app', '0002_remove_chat_receiver_remove_chat_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_history_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ss_app.chat_history'),
        ),
    ]
